# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:30"
      timezone: "UTC"
    target-branch: "next"
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
