comment:
  header: Hi, there.
  footer: "\n\n > This is an automated comment. Responding to the bot or mentioning it won't have any effect.\n\n"

labels:
  - name: invalid ⚠️
    labeled:
      issue:
        body: Please follow the issue templates.
        action: close
      pr:
        body: Thank you @{{ pull_request.user.login }} for suggesting this. Please follow the pull request templates.
        action: close
    unlabeled:
      issue:
        body: Thank you for following the template. The repository owner will reply.
        action: open
  - name: Q&A ✍️
    labeled:
      issue:
        body: |
          Please ask questions at the Github discussions.
          https://github.com/z-shell/zi/discussions/categories/q-a
        action: close
  - name: priority-low 🔖
    labeled:
      issue:
        body: "This issue currently can't be resolved, but we appreciate your contribution."
        action: close
    unlabeled:
      issue:
        body: This issue may be useful and has become active again.
        action: open
  - name: beginner-friendly 💕
    labeled:
      issue:
        body: This issue is easy for contributing. Good for people wanting to contribute to this project.
  - name: feature-request 💡
    labeled:
      issue:
        body: Thank you @{{ issue.user.login }} for suggesting this.
  - name: locked ‼️
    labeled:
      issue:
        body: |
          This issue has been **LOCKED** because of spam!

          Please do not spam messages and/or issues on the issue tracker. You may get blocked from this repository for doing so.
        action: close
        locking: lock
        lock_reason: spam
      pr:
        body: |
          This pull-request has been **LOCKED** because of spam!

          Please do not spam messages and/or pull-requests on this project. You may get blocked from this repository for doing so.
        action: close
        locking: lock
        lock_reason: spam
  - name: resolved ☑️
    labeled:
      issue:
        body: |
          This issue has been **LOCKED** because of it being resolved!

          The issue has been fixed and is therefore considered resolved.
          If you still encounter this or it has changed, open a new issue instead of responding to solved ones.
        action: close
        locking: lock
        lock_reason: resolved
