---
- name: "breaking-change 💥"
  color: d93f0b
  description: "A change that changes the API or breaks backward compatibility for users."
- name: "bug 🐞"
  color: b60205
  description: "Inconsistencies or issues which will cause a problem for users or implementors."
- name: "documentation 📝"
  color: 0052cc
  description: "Solely about the documentation of the project."
- name: "enhancement ✨"
  color: 006b75
  description: "Enhancement of the code, not introducing new features."
- name: "refactor ♻️"
  color: 006b75
  description: "Simplified code that is easier to understand or more efficient syntax or methods."
- name: "performance 🚀"
  color: 1d76db
  description: "Improving performance of the project, not introducing new features."
- name: "new-feature 🎉"
  color: 0e8a16
  description: "Introduces new feature"
- name: "security 🛡️"
  color: ee0701
  description: "Addressing a vulnerability or security risk in this project."
- name: "maintenance 📈"
  color: 531999
  description: "Generic maintenance tasks."
- name: "ci 🤖"
  color: 5319e7
  description: "Work that improves the continuous integration."
- name: "dependencies 📦"
  color: fbca04
  description: "Change in project dependencies."
- name: "submodules ⚙️"
  color: fbca04
  description: "Change in project dependencies."

- name: "in-progress ⚡"
  color: f510f4
  description: "Issue is currently being worked on by a developer."
- name: "triage 📑"
  color: fbca04
  description: "The issue is awaiting investigation."
- name: "stale 👻"
  color: ffffff
  description: "No activity for quite some time."
- name: "no-stale 🔒"
  color: fef2c0
  description: "This is exempt from the stale bot"

- name: "Q&A ✍️"
  color: fef2c0
  description: "Questions and answers."
- name: "invalid ⚠️"
  color: 0b467f
  description: "This is off-topic or incorrect."
- name: "beginner-friendly 💕"
  color: 0e8a16
  description: "Good first issue for people wanting to contribute to this project."
- name: "help-wanted 👥"
  color: 832Aeb
  description: "We need some extra helping hands or expertise in order to resolve this!"
- name: "feature-request 💡"
  color: 0e8a16
  description: "Suggests new feature."
- name: "locked ‼️"
  color: d93f0b
  description: "Spam, inappropriate or otherwise doesn't apply to this project."
- name: "resolved ☑️"
  color: 0e8a16
  description: "The issue has been fixed and is therefore considered resolved."
#- name: "priority-hight 🔥"
#  color: ee0701
#  description: "Must be addressed as soon as possible."
#- name: "priority-medium 📌"
#  color: fbcA04
#  description: "This issue may be useful, and needs some attention."
- name: "priority-low 🔖"
  color: ffffff
  description: "This issue currently can't be resolved."

#- name: "annex 💠"
#  color: 3e16f3
#  description: "Related with annex"
#- name: "plugin 🧿"
#  color: 3e16f3
#  description: "Related with plugin"
#- name: "package 📦"
#  color: 3e16f3
#  description: "Related with package"

#- name: "major 🔺"
#  color: b60205
#  description: "This PR causes a major bump in the version number."
#- name: "minor 🔸"
#  color: 5319e7
#  description: "This PR causes a minor bump in the version number."
