#!/usr/bin/env bash

old_ref="$1"
new_ref="$2"
branch_switched="$3"

if [[ $branch_switched != '1' ]]; then
    exit 0
fi

echo "=== POST CHECKOUT ==="
current_branch="$(git rev-parse --abbrev-ref HEAD)"
hook_dir="$(dirname $0)"
root_dir="$(pwd -P)"
info_dir="$root_dir/.git/info"
exclude_target='.gitignore'

if [[ -f "${root_dir}/${exclude_target}.${current_branch}" ]]; then
	echo -e "Use .gitignore.${current_branch} to exclude files"
    exclude_target=.gitignore.${current_branch}
fi

builtin cd "$info_dir" || exit
rm exclude
echo -e "Copy .gitignore.${current_branch} where required"
cp "${root_dir}/${exclude_target}" exclude
echo -e "=== POST CHECKOUT END ==="
