name: "Bug report 🐞"
description: File a bug report
labels: ["bug 🐞"]
title: "bug: "
body:
  - type: markdown
    attributes:
      value: |
        First off, thanks for taking the time to contribute! Contributions are what make the open-source community such an amazing place to learn, inspire, and create. Any contributions you make will benefit everybody else and are greatly appreciated.

  - type: input
    id: environment
    attributes:
      label: Environment
      description: >
        Your environment details with: echo "${OSTYPE}|$(uname -m)|${ZSH_VERSION}"
      placeholder: "linux-gnu|x86_64|5.8"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Current behavior
      description: "Describe how the bug manifests"
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: "Explain the steps required to duplicate the issue"
    validations:
      required: true

  - type: textarea
    id: code-snippet
    attributes:
      label: Code snippet
      description: "Please insert your zshrc or just a short code snippet in concern"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Aditional information
      description: "List any other information that is relevant to your issue. For reports and stats run `zi analytics`"
    validations:
      required: true
