name: "Feature request 💡"
description: Suggest an idea for this project
labels: ["feature-request 💡"]
title: "feat: "
body:
  - type: markdown
    attributes:
      value: |
        First off, thanks for taking the time to contribute! Contributions are what make the open-source community such an amazing place to learn, inspire, and create. Any contributions you make will benefit everybody else and are greatly appreciated.

  - type: input
    id: description
    attributes:
      label: Feature description
      description: A clear and concise description of what the feature request is. Please include if your feature request is related to a problem
    validations:
      required: true

  - type: dropdown
    id: assistance
    attributes:
      label: "If the feature request is approved, would you be willing to submit a PR? (Help can be provided if you need assistance submitting a PR)"
      options:
        - "Yes"
        - "no"
    validations:
      required: true

  - type: textarea
    id: code-snippet
    attributes:
      label: Related Code
      description: "If you are able to illustrate the bug or feature request with an example, please provide it here"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: "List any other information that is relevant to your issue. Stack traces, related issues, suggestions on how to add, use case, Stack Overflow links, forum links, screenshots, OS if applicable, etc."
    validations:
      required: false
