name: "💡 Feature request"
description: Propose a new Zi capability
title: "[feat]: "
labels: ["type:feature", "status:triage"]
assignees: ["ss-o"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What Zi use case is difficult or impossible today?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the behavior and show an example Zi command or configuration.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false
  - type: checkboxes
    id: self-service
    attributes:
      label: Self-service
      options:
        - label: I would be willing to implement this feature.
  - type: checkboxes
    id: policies
    attributes:
      label: Project policies
      options:
        - label: I have read the [contribution guidelines](https://github.com/z-shell/.github/blob/main/.github/CONTRIBUTING.md).
          required: true
        - label: I agree to follow the [Code of Conduct](https://github.com/z-shell/.github/blob/main/.github/CODE_OF_CONDUCT.md).
          required: true
