name: "✨ Codebase improvement"
description: Suggest a better solution for algorithms, annexea, packages, development tools, etc.
title: "[dev]: "
labels: ["enhancement ✨"]
body:
  - type: textarea
    id: enhancement
    attributes:
      label: "Your feedback for the existing codebase"
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        First off, thanks for taking the time to contribute!
        Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
        Any contributions you make will benefit everybody else and are greatly appreciated.
  - type: checkboxes
    attributes:
      label: Self-service
      description: |
        If you feel like you could contribute to this issue, please check the box below. This would tell us and other people looking for contributions that someone's working on it.
        If you do check this box, please send a pull request within 7 days so we can still delegate this to someone else.
      options:
        - label: I'd be willing to address this documentation request myself.
  - type: checkboxes
    attributes:
      label: Have you read the Contributing Guidelines?
      options:
        - label: I have read the [Contributing Guidelines](https://github.com/z-shell/community/blob/main/docs/CONTRIBUTING_GUIDELINES.md).
          required: true
  - type: checkboxes
    attributes:
      label: Are you familiar with Contributor Covenant Code of Conduct?
      options:
        - label: I have read the [Contributor Covenant Code of Conduct](https://github.com/z-shell/zi/blob/main/docs/CODE_OF_CONDUCT.md).
          required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
