name: "📚 Documentation"
description: Request a correction or improvement to Zi documentation
title: "[docs]: "
labels: ["type:docs", "area:docs"]
assignees: ["ss-o"]
body:
  - type: dropdown
    id: area
    attributes:
      label: Documentation area
      options:
        - Zi repository
        - Wiki
        - Annexes
        - Plugins
        - Packages
        - Other
    validations:
      required: true
  - type: input
    id: location
    attributes:
      label: Location
      description: Link to the page or identify the file and section.
    validations:
      required: true
  - type: textarea
    id: request
    attributes:
      label: Requested change
      description: Explain what is missing, unclear, or incorrect and suggest replacement wording if possible.
    validations:
      required: true
  - type: checkboxes
    id: self-service
    attributes:
      label: Self-service
      options:
        - label: I would be willing to update this documentation.
  - type: checkboxes
    id: policies
    attributes:
      label: Project policies
      options:
        - label: I have read the [contribution guidelines](https://github.com/z-shell/.github/blob/main/.github/CONTRIBUTING.md).
          required: true
        - label: I agree to follow the [Code of Conduct](https://github.com/z-shell/.github/blob/main/.github/CODE_OF_CONDUCT.md).
          required: true
