name: 📚 Documentation
description: Report an issue related to documentation
labels: [dependencies 📦]
title: "docs: "
body:
  - type: markdown
    attributes:
      value: |
        This template is strictly used for documentation requests, including:

        - Elaborating on a particular topic;
        - Updating external links;
        - anything else that doesn't require touching the codebase itself.

        If you followed the documentation but things don't work, take some time to consider if it's the documentation or the code that's wrong. In the latter, prefer using the "bug" template.

        You may proceed directly to sending a pull request without filing this issue, and we can improve on your work.
        If you think some of the requirements above are not met, or if you are not able to contribute yourself, the issue is still welcomed.

  - type: checkboxes
    attributes:
      label: Have you read the Contributing Guidelines?
      options:
        - label: I have read the [Contributing Guidelines](https://github.com/z-shell/zi/blob/main/docs/CONTRIBUTING.md).
          required: true

  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the issue is.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Self-service
      description: |
        If you feel like you could contribute to this issue, please check the box below. This would tell us and other people looking for contributions that someone's working on it.
        If you do check this box, please send a pull request within 7 days so we can still delegate this to someone else.
      options:
        - label: I'd be willing to address this documentation request myself.
