---
name: Trunk Code Quality
on:
  push:
    branches: [main, next]
    tags: ["v*.*.*"]
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  check:
    permissions:
      contents: read
    uses: z-shell/.github/.github/workflows/trunk.yml@6fac3d47a61b27db54e50a0519c1e79b2935eda4 # main
    with:
      check-mode: all
