---
name: ZD Integration

on:
  push:
    branches: [main, next]
    paths:
      - ".github/workflows/zd-integration.yml"
      - "zi.zsh"
      - "lib/**"
  pull_request:
    paths:
      - ".github/workflows/zd-integration.yml"
      - "zi.zsh"
      - "lib/**"
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  zd-test:
    uses: z-shell/zd/.github/workflows/test-native.yml@fd0995d6f7958fea6c4abbc4fff81a6da2277b66 # z-shell/zd#95, #96, #107
    with:
      zi_repo: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
      zi_ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
      include_compat: false
